[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
op_sepolia = "${OP_SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { url = "${BLOCKSCOUT_BASE_SEPOLIA_URL}", verifier = "blockscout" }
op_sepolia = { url = "${BLOCKSCOUT_OP_SEPOLIA_URL}", verifier = "blockscout" }
sepolia = { url = "${BLOCKSCOUT_SEPOLIA_URL}", verifier = "blockscout" }
